P1 = fractal
#Choose either the C compiler or the C++ compiler from the following 2 lines
CC = gcc
CPP = g++
CFLAGS = -g -Wall
OMPFLAG = -fopenmp
PNG = -lpng
#INCFLAG = -I "../common/"

all: $(P1)

$(P1): $(P1).cpp
	$(CPP) $(CFLAGS) $(OMPFLAG) $(P1).cpp $(PNG) -o $(P1)

clean:
	rm -vf $(P1)
